### ISSUE TITLE
Linux errors

### ISSUE THREAD

**Issue by Danfun64** [zenorogue/noteye#4]
Note that I am running an x86_64 system...

Compiling Noteye was easy enough. sudo make install gave this error:

`bash -c "cd ../sound; install -D -m 744 -t \"/usr/share/noteye/sound/\" *.ogg"
install: cannot stat '*.ogg': No such file or directory
`

Copying the sounds from the hydra-old folder fixed the problem, but when I tried to run noteye, I got this error

`could not load size 2 of /usr/share/noteye/gfx/Inconsolata.otf
NotEye error #21: dofile [/usr/share/noteye/common/fonts.noe:63: attempt to index local 'size' (a nil value)]
`

The main reason I wanted noteye is to play your version of brogue. Per your instructions, I installed noteye first and then started compiling brogue-noteye. That had its own problems...

https://paste.debian.net/hidden/9ecc9804/

Any suggestions?

Also running the i386 binary that comes with the package is very laggy for some reason, yet I could handle games that in theory should be far more graphically advanced just fine.

**Comment by zenorogue** [comment]
Thanks! I have fixed the install command.

The warnings are from Brogue itself (I have not changed anything there). Possibly the fixed install command will fix the undefined reference to MIX_HaltMusic; if not, try adding -lSDL2_mixer to the line SDL_FLAGS in Brogue's Makefile. Does this fix the problem?

**Comment by Danfun64** [comment]
Thanks for fixing noteye!

Adding -lSDL2_mixer in Brogue's Makefile fixed that issue. I also removed the instance of "-march=i586" from it as well.

Running Noteye Brogue natively reduced the lag issues, but its still not as fluid as i'd like it to be. Do you have any suggestions on reducing the lag further?

**Comment by zenorogue** [comment]
Thanks! I have posted the modifications to Makefile on http://www.roguetemple.com/z/noteye/brogue.php I have also posted a new brogue.noe which fixes a bug and improves the efficiency.

It runs very well on my machine (there is a lag if you are playing with arrows keys, but that's only because NotEye waits to make sure that you don't want to go diagonally -- this can be disabled with Ctrl+M K D). What mode are you using? Any specific settings?

**Comment by Danfun64** [comment]
I'm mainly referring to graphical lag. Not sure how to describe it, but sometimes it shudders, sometimes it skips around. The effect is worse in 3d modes of course, but its still rather annoying in tiles or plain mode. It also seems to get worse in watery areas. As I mentioned before, the affect is worse when running the 32-bit linux file, and even worse using the 32-bit windows file in wine.

**Comment by Danfun64** [comment]
...still can't figure it out?

**Comment by zenorogue** [comment]
Regarding the shuddering -- you could try to use the "careless" setting (Ctrl+M o q), most players prefer it that way (actually this is the default setting now -- the previous default setting made the animation faster if you pressed keys quickly, which looked like shuddering/skipping).

Also the newest version of NotEye in the repo has switched to use LuaJIT instead of Lua -- this might help too since LuaJIT is much more efficient.
